/*
 * FindEmptyRoom.java
 *
 * Created on __DATE__, __TIME__
 */

package Main;

import java.util.List;

import AllDao.RoomTypeDao;
import AllDao.SearchRoomTypeDao;

import model.RoomTypeModel;

/**
 *
 * @author  __USER__
 */
public class FindEmptyRoom extends javax.swing.JInternalFrame {

	/** Creates new form FindEmptyRoom */
	RoomTypeDao rtdao = new RoomTypeDao();
	SearchRoomTypeDao srtdao = new SearchRoomTypeDao();

	/** Creates new form FindEmptyRoom */
	public FindEmptyRoom() {
		initComponents();
		this.jComboBox1.removeAllItems();
		this.fillRoomType();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jComboBox1 = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();

		setClosable(true);
		setIconifiable(true);
		setMaximizable(true);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel1.setText("\u7c7b\u578b\u540d\u79f0\uff1a");

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Main/images/search.png"))); // NOI18N
		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabel2.setText("\u7a7a\u623f\u67e5\u8be2");

		jLabel3.setText("\u7a7a\u623f\u6570\u91cf\uff1a");

		jLabel4.setText("\u623f\u95f4\u5355\u4ef7\uff1a");

		jLabel5.setText("\u623f\u95f4\u9762\u79ef\uff1a");

		jLabel6.setText("**\u95f4");

		jLabel7.setText("80.00\uffe5");

		jLabel8.setText("30\u5e73\u65b9\u7c73");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(33, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel2)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel3)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jLabel6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								46,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel1)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jComboBox1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								102,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel4)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jLabel7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								61,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel5)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jLabel8))))
										.addGap(18, 18, 18)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												93,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1))
										.addGap(30, 30, 30)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jLabel6))
										.addGap(27, 27, 27)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(jLabel7))
										.addGap(36, 36, 36)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(jLabel8))
										.addContainerGap(66, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		RoomTypeModel RomTy = (RoomTypeModel) this.jComboBox1.getSelectedItem();
		String roomtype = RomTy.getRName();
		RoomTypeModel rommol = new RoomTypeModel(roomtype);
		List<RoomTypeModel> listroom = srtdao.list(rommol);
		RoomTypeModel room1 = null;
		if (listroom.size() != 0) {
			room1 = listroom.get(0);
			this.jLabel6.setText(room1.getREmptyCount()+" 间");
			this.jLabel7.setText(room1.getKPrice()+" ￥");
			this.jLabel8.setText(room1.getRAre()+" 平方米");
		}

	}

	private void fillRoomType() {
		try {
			List<RoomTypeModel> room = rtdao.list(new RoomTypeModel());
			RoomTypeModel roomtp = null;
			roomtp = new RoomTypeModel();
			roomtp.setRName("请选择...");
			this.jComboBox1.addItem(roomtp);
			if (room.size() != 0) {
				for (int i = 0; i < room.size(); i++) {
					roomtp = room.get(i);
					this.jComboBox1.addItem(roomtp);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
		}
	}

	

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	// End of variables declaration//GEN-END:variables

}