/*
 * inhotel.java
 *
 * Created on __DATE__, __TIME__
 */

package Main;

import java.awt.Checkbox;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import util.StringUtil;

import model.BookRoomModel;
import model.CheckinhotelModel;
import model.RoomTypeModel;
import model.User;
import model.ZhinforModel;
import AllDao.AddZhInfromDao;
import AllDao.CheckinDao;
import AllDao.RoomTypeDao;
import AllDao.SearchRoomTypeDao;

/**
 *
 * @author  __USER__
 */
public class inhotel extends javax.swing.JInternalFrame {

	/** Creates new form inhotel */
	RoomTypeDao rmtydao = new RoomTypeDao();
	SearchRoomTypeDao seachroomtypedao = new SearchRoomTypeDao();
	CheckinDao checkdao = new CheckinDao();
	AddZhInfromDao adzhxxdao = new AddZhInfromDao();

	public inhotel() {
		initComponents();
	}

	public inhotel(String QID) {
		initComponents();
		jLabel8.setText(QID);
		this.jComboBox1.removeAllItems();
		this.fillRoomType();
		fillTable(new RoomTypeModel());
		SimpleDateFormat sdf = new SimpleDateFormat(" yyyy-MM-dd HH:mm:ss ");
		String nowtime = sdf.format(new java.util.Date());
		jLabel10.setText(nowtime);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jButton2 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setClosable(true);
		setIconifiable(true);
		setMaximizable(true);

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u6536\u7d22\u623f\u95f4\u6761\u4ef6"));

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		jLabel1.setText("\u623f\u95f4\u7c7b\u578b\uff1a");

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Main/images/search.png"))); // NOI18N
		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(48, 48, 48)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jComboBox1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												89,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(269, 269, 269)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												108,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(54, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel1)
														.addComponent(jButton1))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel3.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u5f55\u5165\u4f4f\u6237\u4fe1\u606f"));

		jLabel4.setText("\u623f\u95f4\u7f16\u53f7\uff1a");

		jLabel5.setText("\u4f4f\u6237\u59d3\u540d\uff1a");

		jLabel6.setText("\u4f4f\u6237\u7f16\u53f7\uff1a");

		jLabel7.setText("\u8eab\u4efd\u8bc1\u53f7\uff1a");

		jLabel9.setText("\u5f53\u524d\u65e5\u671f\uff1a");

		jLabel10.setText("----|----|----");

		jCheckBox1.setText("  \u662f\u5426\u4f1a\u5458");

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Main/images/check.png"))); // NOI18N
		jButton2.setText("\u767b\u8bb0\u5165\u4f4f");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				73,
																				Short.MAX_VALUE)
																		.addGap(
																				26,
																				26,
																				26)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel7))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextField5,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								167,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								167,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								120,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				69,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel9)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel10))
														.addComponent(
																jCheckBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																92,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(125, 125, 125)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9)
														.addComponent(jLabel10))
										.addGap(31, 31, 31)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7)
														.addComponent(jLabel5)
														.addComponent(
																jTextField5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jCheckBox1))
										.addGap(18, 18, 18)
										.addComponent(
												jButton2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												43,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Main/images/qiantai.png"))); // NOI18N
		jLabel3.setText("\u524d\u53f0\u7f16\u53f7\uff1a");

		jLabel8.setText("jLabel8");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "房间编号",
						"是否电脑房", "价格（￥/晚）", "面积（m2）" }));
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTable1MouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jPanel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																655,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel8)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(40, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jLabel8))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												120,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:

		int rowIndex = jTable1.getSelectedRow();
		String roomnum = String.valueOf(jTable1.getModel().getValueAt(rowIndex,
				0));
		this.jTextField2.setText(roomnum);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		RoomTypeModel RomTy = (RoomTypeModel) this.jComboBox1.getSelectedItem();
		String roomtype = RomTy.getRName();
		RoomTypeModel bkrommol = new RoomTypeModel(roomtype);
		this.fillTable(bkrommol);
	}

	private void fillTable(RoomTypeModel romtpmod) {
		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
		dtm.setRowCount(0);
		try {
			List<RoomTypeModel> listromtype = seachroomtypedao.list(romtpmod);
			RoomTypeModel tyrom = null;
			if (listromtype.size() != 0) {
				for (int i = 0; i < listromtype.size(); i++) {
					tyrom = listromtype.get(i);
					Vector v = new Vector();
					v.add(tyrom.getKId());
					v.add(tyrom.getKComputer());
					v.add(tyrom.getKPrice());
					v.add(tyrom.getRAre());
					dtm.addRow(v);
				}
			}
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		String fjbh = this.jTextField2.getText();

		String zhbh = this.jTextField4.getText();
		String nowtime = this.jLabel10.getText();
		String zname = this.jTextField3.getText();
		String zsid = this.jTextField5.getText();
		String zmember;

		if (jCheckBox1.isSelected()) {
			zmember = "1";
		} else {
			zmember = "0";
		}
		if (StringUtil.isEmpty(fjbh)) {
			JOptionPane.showMessageDialog(null, "请选择入住房间！ ");
			return;
		}
		String szm = fjbh.substring(0, 1);
		if (!szm.equals("K")) {
			JOptionPane.showMessageDialog(null, "房间号错误 ");
			return;
		}
		if (StringUtil.isEmpty(zhbh)) {
			JOptionPane.showMessageDialog(null, "请输入住户编号，例：Z1001 ");
			return;
		}
		String zhh = zhbh.substring(0, 1);
		if (!zhh.equals("Z")) {
			JOptionPane.showMessageDialog(null, "请规范填写住户编号!");
			return;
		}
		if (StringUtil.isEmpty(zname)) {
			JOptionPane.showMessageDialog(null, "请输入住户人名字！ ");
			return;
		}
		if (StringUtil.isEmpty(zsid)) {
			JOptionPane.showMessageDialog(null, "请输入住户人身份证！ ");
			return;
		}
		String sfzhmyz = "(^\\d{18}$)|(^\\d{15}$)";
		if (zsid.length() != 18) {
			JOptionPane.showMessageDialog(null, "身份证号码应该18位！ ");
			return;
		} else {
			Pattern p = Pattern.compile(sfzhmyz);
			Matcher m = p.matcher(zsid);
			boolean isMatch = m.matches();
			if (isMatch == false) {
				JOptionPane.showMessageDialog(null, "请输入正确的身份证号码！ ");
				return;
			}
		}

		java.sql.Date date;
		ZhinforModel zhxx;
		try {

			date = new java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(
					nowtime).getTime());
			zhxx = new ZhinforModel(zname, zsid, zhbh, date, zmember);
			int countNum = adzhxxdao.add(zhxx);
			if (countNum == 1) {
				JOptionPane.showMessageDialog(null, "住户信息录入成功！");
			} else {
				JOptionPane.showMessageDialog(null, "住户信息录入失败！");
			}
		} catch (ParseException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
			JOptionPane.showMessageDialog(null, "住户信息录入1失败！");
		}

		String qid = this.jLabel8.getText();
		String kid = this.jTextField2.getText();
		String zid = this.jTextField4.getText();

		CheckinhotelModel ckingl;
		ckingl = new CheckinhotelModel(qid, kid, zid);
		int addNum = checkdao.add(ckingl);
		if (addNum == 1) {
			JOptionPane.showMessageDialog(null, "成功入住！");
			this.jTextField4.setText("");
			this.jTextField5.setText("");
			this.jTextField2.setText("");
			this.jTextField3.setText("");

		} else {
			JOptionPane.showMessageDialog(null, "入住失败！");
		}

	}

	private void fillRoomType() {
		try {
			List<RoomTypeModel> room = rmtydao.list(new RoomTypeModel());
			RoomTypeModel roomtp = null;
			roomtp = new RoomTypeModel();
			roomtp.setRName("请选择...");
			this.jComboBox1.addItem(roomtp);
			if (room.size() != 0) {
				for (int i = 0; i < room.size(); i++) {
					roomtp = room.get(i);
					this.jComboBox1.addItem(roomtp);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	// End of variables declaration//GEN-END:variables

}